### ISSUE TITLE
scalr get-plan-log returns invalid character error

### ISSUE THREAD

**Issue by clrung** [Scalr/scalr-cli#72]
When I attempt to fetch the plan log for a plan, I get an error.
```
❯ scalr get-plan-log -plan plan-[redacted]
invalid character '\x02' looking for beginning of value
```
I am able to perform other operations, such as `scalr get-plan`.

**Comment by buzzy** [comment]
Sorry for late reply! Please try the latest version 0.15.5 and see if that one solves your issue. Thanks!

**Comment by clrung** [comment]
> Sorry for late reply! Please try the latest version 0.15.5 and see if that one solves your issue. Thanks!

Thank you, @buzzy! I updated to `0.15.5` and can confirm that I now see the plan logs as I expect 🙌🏼  I appreciate it!
