### ISSUE TITLE
List Environments Not Working

### ISSUE THREAD

**Issue by rtfee** [Scalr/scalr-cli#8]
User has the proper permissions, but gets the following:

`scalr list-environments`
`
{
  "id": null,
  "type": null
}`

**Comment by rtfee** [comment]
Actually, this ended up being a user error. The problem was that the user did not actually have the right permissions. Wondering if we can reflect that in the response?

**Comment by buzzy** [comment]
Please run it again with -verbose and post the output. I will look into a better error message for it.

**Comment by buzzy** [comment]
Fixed in 0.6.0
